# Site settings
title: Izabela Guerreiro
header-img: img/home-bg.jpg
email: izaguerreiro@gmail.com
description: "Blog pessoal, que tratará de assuntos relacionados a Tecnologia da Informação."
baseurl: ""
url: "http://izaguerreiro.me"
twitter_username: izaguerreiro
github_username:  izaguerreiro
linkedin_username: in/izabela-guerreiro-1ba49838
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
